### ISSUE TITLE
Unable to run using offline mode

### ISSUE THREAD

**Issue by smilernet** [DiogoAndre/acl_stats#3]
* ACL Stats version: Latest ACL Stats version from GitHub (0.1.2)
* Python version: Python 3.6.9
* Operating System: Ubuntu 18.04 LTS

Trying to run acl_stats in offline mode

acl_stats static --acl-file acl.log --acl-brief acl_brief.log --output json --write-to acl-inside_in.csv

ACL Stats
Using Static Files
acl.log
acl_brief.log
json
acl-inside_in.csv

Contacting Device
Fetching ACL
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f06566a1240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: /admin/exec/show+access-list+None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f06566a1240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/acl_stats/acl_stats.py", line 71, in get_resp
    params=params, verify=False)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: /admin/exec/show+access-list+None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f06566a1240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./acl_stats", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/acl_stats/cli.py", line 30, in static
    ACLStats.process_live()
  File "/usr/local/lib/python3.6/dist-packages/acl_stats/acl_stats.py", line 207, in process_live
    acl = fetcher.get_resp(endpoint=acl_endpoint)
  File "/usr/local/lib/python3.6/dist-packages/acl_stats/acl_stats.py", line 85, in get_resp
    raise Exception(e)
Exception: HTTPSConnectionPool(host='none', port=443): Max retries exceeded with url: /admin/exec/show+access-list+None (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f06566a1240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

**Comment by Newbie27** [comment]
how was this solved?

**Comment by mrdc82** [comment]
it doesnt appear to have been solved. when using static files, the script makes an attempt to connect to a device instead of only using the static files specified.
